config/routes.rb
Rails.application.routes.draw do

  root "shops#index"

  get 'shops/index'
  get 'suppliers/order_index', to: 'suppliers#order_index'
  get 'buys/order_index', to: 'buys#order_index'
  get 'buys/search', to: 'buys#search'
  get 'buys/search_result', to: 'buys#search_result'
  get 'buys/issue_receipt', to: 'buys#issue_receipt'
  get 'buys/receipt', to: 'buys#receipt'
  get 'customers/order_index', to: 'customers#order_index'
  get 'sells/order_index', to: 'sells#order_index'
  get 'sells/search', to: 'sells#search'
  get 'sells/search_result', to: 'sells#search_result'
  get 'sells/issue_receipt', to: 'sells#issue_receipt'
  get 'sells/receipt', to: 'sells#receipt'
  get 'items/search', to: 'items#search'
  get 'items/buy_receipt', to: 'items#buy_receipt'
  get 'items/sell_receipt', to: 'items#sell_receipt'
  get 'categories/search', to: 'categories#search'
  get 'categories/buy_receipt', to: 'categories#buy_receipt'
  get 'categories/sell_receipt', to: 'categories#sell_receipt'


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: :show

  resources :categories do
    get 'items', to: 'categories#items'
    collection do
      post 'import', to: 'categories#import'
    end
  end

  resources :items do
    member do
      get 'details'
    end
    collection do
      post 'import'
    end
  end
  resources :suppliers do
    collection do
      post 'import'
    end
    resources :buys do
    end
  end
  resources :customers do
    collection do
      post 'import'
    end
    resources :sells do
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<div class="top-page-container">

  <!-- サイドバー -->
  <div class="side-bar">
    <div class="contents">
      <div class="top-menu">
        新規登録
      </div>
      <div>
        <p><%= link_to '仕入れ先登録', new_supplier_path %></p>
        <p><%= link_to '得意先登録', new_customer_path %></p>
        <p><%= link_to 'カテゴリ登録', new_category_path %></p>
        <p><%= link_to '商品登録', new_item_path %></p>
      </div>
    </div>
    <div class="contents">
      <div class="top-menu">
        登録済リスト
      </div>
      <div>
        <p><%= link_to '仕入れ先一覧', suppliers_path %></p>
        <p><%= link_to '得意先一覧', customers_path %></p>
        <p><%= link_to 'カテゴリ一覧', categories_path %></p>
        <p><%= link_to '商品一覧', items_path %></p>
      </div>
    </div>
    <div class="contents">
      <div class="top-menu">
        集計
      </div>
      <div>
        <p><%= link_to '仕入れ先別', buys_search_path %></p>
        <p><%= link_to '得意先別', sells_search_path %></p>
        <p><%= link_to 'カテゴリ別', categories_search_path %></p>
        <p><%= link_to '商品別', items_search_path %></p>
      </div>
    </div>
  </div>

  <!-- メイン -->
  <div class="top-main">
    <div class="contents">
      <div class="top-menu">
        仕入れ関連
      </div>
      <div>
        <p><%= link_to '発注書作成', suppliers_order_index_path, class: "btn" %></p>
        <p><%= link_to '発注履歴', buys_order_index_path, class: "btn" %></p>
        <p><%= link_to '支払明細書作成', buys_issue_receipt_path, class: "btn" %></p>
      </div>
    </div>
    <div class="contents">
      <div class="top-menu">
        納品関連
      </div>
      <div>
        <p><%= link_to '納品書作成', customers_order_index_path, class: "btn" %></p>
        <p><%= link_to '納品履歴', sells_order_index_path, class: "btn" %></p>
        <p><%= link_to '請求書作成', sells_issue_receipt_path, class: "btn" %></p>
      </div>
    </div>
  </div>
</div>