config/routes.rb
Rails.application.routes.draw do

  root "shops#index"

  get 'shops/index'
  get 'suppliers/order_index', to: 'suppliers#order_index'
  get 'buys/order_index', to: 'buys#order_index'
  get 'buys/search', to: 'buys#search'
  get 'buys/search_result', to: 'buys#search_result'
  get 'buys/issue_receipt', to: 'buys#issue_receipt'
  get 'buys/receipt', to: 'buys#receipt'
  get 'customers/order_index', to: 'customers#order_index'
  get 'sells/order_index', to: 'sells#order_index'
  get 'sells/search', to: 'sells#search'
  get 'sells/search_result', to: 'sells#search_result'
  get 'sells/issue_receipt', to: 'sells#issue_receipt'
  get 'sells/receipt', to: 'sells#receipt'
  get 'items/search', to: 'items#search'
  get 'items/buy_receipt', to: 'items#buy_receipt'
  get 'items/sell_receipt', to: 'items#sell_receipt'
  get 'categories/search', to: 'categories#search'
  get 'categories/buy_receipt', to: 'categories#buy_receipt'
  get 'categories/sell_receipt', to: 'categories#sell_receipt'


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: :show

  resources :categories do
    get 'items', to: 'categories#items'
    collection do
      post 'import', to: 'categories#import'
    end
  end

  resources :items do
    member do
      get 'details'
    end
    collection do
      post 'import'
    end
  end
  resources :suppliers do
    collection do
      post 'import'
    end
    resources :buys do
    end
  end
  resources :customers do
    collection do
      post 'import'
    end
    resources :sells do
    end
  end
end

app/models/buy.rb
class Buy < ApplicationRecord
  validates :transaction_date, presence: true

  belongs_to :user
  belongs_to :supplier
  has_many :buy_items, inverse_of: :buy, dependent: :destroy
  has_many :items, through: :buy_items

  accepts_nested_attributes_for :buy_items, allow_destroy: true
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  def order_index
    @buys = current_user.buys.order("buys.transaction_date DESC")
                             .page(params[:page]).per(20)
  end

  def new
    @supplier = current_user.suppliers.find(params[:supplier_id])
    @buy = current_user.buys.new
    @buy.buy_items.build
    @items = current_user.items
    @categories = current_user.categories
  end

  def create
    @supplier = current_user.suppliers.find(params[:supplier_id])
    @buy = current_user.buys.new(buy_params.merge(supplier_id: @supplier.id))
    @categories = current_user.categories
    if @buy.save
      redirect_to root_path
    else
      @items = current_user.items
      @categories = current_user.categories
      render :new
    end
  end

  def edit
    @buy = current_user.buys.find(params[:id])
    @supplier = @buy.supplier
    @categories = current_user.categories
    @items = current_user.items
  end

  def update
    @buy = current_user.buys.find(params[:id])
    @supplier = @buy.supplier
    @categories = current_user.categories
    @items = current_user.items
    if @buy.update(buy_params)
      redirect_to buys_order_index_path
    else
      render :edit
    end
  end

  def destroy
    buy = current_user.buys.find(params[:id])
    buy.destroy
    redirect_to buys_order_index_path
  end

  def search
    @suppliers = current_user.suppliers.order("suppliers.company ASC")
  end

  def search_result
    @supplier_id = params[:supplier_id]
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @supplier = current_user.suppliers.find(@supplier_id)
    @receipts = current_user.buys.where(supplier_id: @supplier_id)
                                .where("transaction_date >= ?", @start_date)
                                .where("transaction_date <= ?", @end_date)
                                .order("buys.transaction_date ASC")
                                .distinct
  end

  def issue_receipt
    @suppliers = current_user.suppliers.order("suppliers.company ASC")
  end
  
  def receipt
    @user = current_user
    @supplier_id = params[:supplier_id]
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @pay_date = params[:pay_date]
    @supplier = current_user.suppliers.find(@supplier_id)

    @receipts = current_user.buys.where(supplier_id: @supplier_id)
                                .where("transaction_date >= ?", @start_date)
                                .where("transaction_date <= ?", @end_date)
                                .order("buys.transaction_date ASC")
                                .distinct
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'receipt', # 出力されるPDFのファイル名
                template: 'buys/receipt', # テンプレートファイルの指定
                layout: 'layouts/pdf',
                enable_local_file_access: true, # ローカルファイルの読み込みを許可
                enable_internal_file_access: true,
                page_size: 'A5'
                #  orientation: 'Landscape'    # 横向きに設定
      end
    end
  end

  def show
    @user = current_user
    @buy = current_user.buys.find(params[:id])
    @supplier = @buy.supplier
    @categories = current_user.categories
    @items = current_user.items
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'show', # 出力されるPDFのファイル名
               template: 'buys/show', # テンプレートファイルの指定
               enable_local_file_access: true, # ローカルファイルの読み込みを許可
               enable_internal_file_access: true,
               page_size: 'A5'
               #  orientation: 'Landscape'    # 横向きに設定
      end
    end
  end

  private 
  def buy_params
    params.require(:buy).permit(:transaction_date, :total_price, buy_items_attributes: [:id, :item_price, :item_total_price, :quantity, :category_id, :item_id, :destroy])
                        .merge(user_id: current_user.id)
  end

end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/edit.html.erb
<div class="table_container">
  <div class="section-title">
    発注内容の編集(金額入力)
  </div>

  <div class="sub-title">
    <%= @supplier.company %>への発注
  </div>

  <%= form_with(model: [@supplier, @buy], local: true) do |f| %>
    <div>
      <%= f.label :transaction_date, "納品日" %>
      <%= f.date_field :transaction_date, class: "form-group" %>
    </div>

    <table class="table-bordered">
      <thead>
        <tr>
          <th>カテゴリ</th>
          <th>商品</th>
          <th>数量</th>
          <th>単位</th>
          <th>単価</th>
          <th>金額</th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :buy_items do |buy_item_form| %>
          <tr>
            <td><%= buy_item_form.collection_select :category_id, @categories, :id, :category, { prompt: "カテゴリを選択" }, { class: "" } %></td>
            <td><%= buy_item_form.collection_select :item_id, @items, :id, :item_name, { prompt: "商品を選択" }, { class: "" } %></td>
            <td><%= buy_item_form.number_field :quantity, class: 'quantity-edit table-quantity', 'data-id': buy_item_form.index %></td>
            <td class="table-unit" id="unit"><%= @items.find { |item| item.id == buy_item_form.object.item_id }&.unit || "--" %></td>
            <td><%= buy_item_form.text_field :item_price, class: 'item-price-edit table-price', 'data-id': buy_item_form.index %></td>
            <td><%= buy_item_form.text_field :item_total_price, class: 'item-total-price-edit table-price', 'data-id': buy_item_form.index %></td>
          </tr>
        <% end %>  
      </tbody>
      <tfoot>
        <td class="table-total-text"><%= f.label :total_price, '合計' %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= f.text_field :total_price, id: 'total_price_edit', class: 'table-price' %></td>
      </tfoot>
    </table>

    <div class="box-wrap-btn">
      <%= f.submit "更新", class: "box-content" %>
    </div>
  <% end %>

  <div class="back">
    <%= link_to  '前のページに戻る', buys_order_index_path %>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
  // 合計価格の計算
  const calculateTotalPrice = () => {
    let totalPrice = 0;

    // 各商品合計価格を合計
    document.querySelectorAll(".item-total-price-edit").forEach(function(itemTotalPriceElement) {
      let itemTotalPrice = parseFloat(itemTotalPriceElement.value) || 0;
      totalPrice += itemTotalPrice;
    });

    // 合計金額をtotal_price_editフィールドに設定
    document.getElementById("total_price_edit").value = totalPrice;
  };

  // 商品単価と数量から商品合計価格を計算
  const updateItemTotalPrice = (element) => {
    const sellItemRow = element.closest('tr');
    const quantityElement = sellItemRow.querySelector('.quantity-edit');
    const itemPriceElement = sellItemRow.querySelector('.item-price-edit');
    const itemTotalPriceElement = sellItemRow.querySelector('.item-total-price-edit');

    const quantity = parseFloat(quantityElement.value) || 0;
    const itemPrice = parseFloat(itemPriceElement.value) || 0;

    const itemTotalPrice = quantity * itemPrice;
    itemTotalPriceElement.value = itemTotalPrice;

    // 更新後、合計価格を再計算
    calculateTotalPrice();
  };

  // 全てのquantityフィールドにイベントリスナーを追加
  document.querySelectorAll(".quantity-edit").forEach(function(element) {
    element.addEventListener("input", function() {
      updateItemTotalPrice(element);
    });
  });

  // 全てのitem-priceフィールドにイベントリスナーを追加
  document.querySelectorAll(".item-price-edit").forEach(function(element) {
    element.addEventListener("input", function() {
      updateItemTotalPrice(element);
    });
  });

  // 初期ロード時に合計を計算
  calculateTotalPrice();
});
</script>

app/views/buys/issue_receipt.html.erb
<div class="box_container">
  <div class="section-title">
    支払い明細書の作成
  </div>
  <div class="box-center">
    <%= form_with url: buys_receipt_path(format: :pdf), method: :get, html: { target: '_blank' }, local: true do %>
      <div class="box-wrap">
        <%= label_tag :supplier_id, "仕入れ先", class: "box-label" %><br>
        <%= select_tag :supplier_id, options_from_collection_for_select(@suppliers, :id, :company, params.fetch(:supplier_id, 1)), prompt: "仕入れ先を選択", required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :start_date, "開始日", class: "box-label" %><br>
        <%= date_field_tag :start_date, params[:start_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :end_date, "終了日", class: "box-label" %><br>
        <%= date_field_tag :end_date, params[:end_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :end_date, "支払い予定日", class: "box-label" %><br>
        <%= date_field_tag :pay_date, params[:pay_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap-btn">
        <%= submit_tag "作成", class: "box-content" %>
      </div>
    <% end %>
  </div>

  <div class="back", style="text-align:center">
    <%= link_to  '前のページに戻る', root_path %>
  </div>
</div>

app/views/buys/new.html.erb
<div class="table_container">
  <div class="section-title">
    <%= @supplier.company %>に発注する
  </div>

  <%= form_with(model: [@supplier, @buy]) do |f| %>
    <div>
      <%= f.label :transaction_date, "納品日" %>
      <%= f.date_field :transaction_date, class: "form-group" %>
    </div>

    <table class="table-bordered">
      <thead>
        <tr>
          <th>カテゴリ</th>
          <th>商品</th>
          <th>数量</th>
          <th>単位</th>
        </tr>
      </thead>
      <tbody id="buy-item-forms">
        <%= f.fields_for :buy_items do |buy_item_form| %>
          <tr class="buy-item">
            <td><%= buy_item_form.collection_select :category_id, @categories, :id, :category, { prompt: "カテゴリを選択" }, { class: "buy-category-select" } %></td>
            <td><%= buy_item_form.collection_select :item_id, [], :id, :item_name, { prompt: "商品を選択" }, { class: "buy-item-select" } %></td>
            <td class="table-unit"><%= buy_item_form.number_field :quantity, class: 'quantity-input' %></td>
            <td class="table-unit" id="unit">--</td>
          </tr>
        <% end %>  
      </tbody>
    </table>

    <%# 追加ボタン %>
    <button type="button" id="add-form-set" class="add-form">商品を追加</button>
    <p>※金額は、納品書受け取り後に「発注履歴の編集」から入力できます。</p>

    <div class="box-wrap-btn">
      <%= f.submit "作成", class: "box-content" %>
    </div>

  <% end %>

  <div class="back">
    <%= link_to '前のページに戻る', suppliers_order_index_path %>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {
  initializeEvents();

  // フィールドセットを追加するボタンのイベント
  document.getElementById('add-form-set').addEventListener('click', function () {
    addNewFields();
  });

  function initializeEvents() {
    document.querySelectorAll('.buy-category-select').forEach(categorySelect => {
      categorySelect.addEventListener('change', function() {
        const categoryId = this.value;
        const buyItem = this.closest('.buy-item');
        const itemSelect = buyItem.querySelector('.buy-item-select');

        if (categoryId && itemSelect) {
          fetch(`/categories/${categoryId}/items`)
            .then(response => response.json())
            .then(data => {
              itemSelect.innerHTML = '';
              itemSelect.insertAdjacentHTML('beforeend', '<option value="">商品を選択</option>');

              data.items.forEach(item => {
                const option = document.createElement('option');
                option.value = item.id;
                option.textContent = item.item_name;
                itemSelect.appendChild(option);
              });
            })
            .catch(error => console.error('Error fetching items:', error));
        }
      });
    });

    document.querySelectorAll('.buy-item-select').forEach(itemSelect => {
      itemSelect.addEventListener('change', function() {
        const itemId = this.value;
        const buyItem = this.closest('.buy-item');
        const unitSpan = buyItem.querySelector('#unit');

        if (itemId) {
          fetch(`/items/${itemId}/details`)
            .then(response => response.json())
            .then(data => {
              unitSpan.textContent = data.unit;
            })
            .catch(error => console.error('Error fetching item details:', error));
        } else {
          unitSpan.textContent = '--';
        }
      });
    });
  }

  function addNewFields() {
    const existingBuyItems = document.querySelectorAll('.buy-item');
    const newFields = existingBuyItems[0].cloneNode(true);
    const newIndex = existingBuyItems.length;

    newFields.querySelectorAll('input, select').forEach(input => {
      const name = input.getAttribute('name').replace(/\d+/, newIndex);
      const id = input.getAttribute('id').replace(/\d+/, newIndex);
      input.setAttribute('name', name);
      input.setAttribute('id', id);
      input.value = '';
    });

    document.getElementById('buy-item-forms').appendChild(newFields);
    initializeEvents();
  }
});
</script>

app/views/buys/order_index.html.erb
<div class="table_container">
  <div class="section-title">
    発注履歴
  </div>

  <table class="table-bordered">
    <thead>
      <tr>
        <th>発注日</th>
        <th>発注先</th>
        <th>金額</th>
        <th>編集</th>
        <th>削除</th>
        <th>印刷</th>
      </tr>
    </thead>
    <tbody>
      <% @buys.each do |buy| %>
        <tr>
          <td class="table-day"><%= buy.transaction_date %></td>
          <td class="table-name"><%= buy.supplier.company %></td>
          <td class="table-price"><%= buy.total_price %></td>
          <td class="table-link"><%= link_to '編集', edit_supplier_buy_path(supplier_id: buy.supplier_id, id: buy.id) %></td>
          <td class="table-link"><%= link_to '削除', supplier_buy_path(supplier_id: buy.supplier_id, id: buy.id), method: :delete, data: { confirm: '削除してもよろしいですか？' } %></td>
          <td class="table-link"><%= link_to '印刷', supplier_buy_path(supplier_id: buy.supplier_id, id: buy.id, format: :pdf), target: '_blank' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @buys %>

  <div class="back">
    <%= link_to  '前のページに戻る', root_path %>
  </div>
</div>

app/views/buys/receipt.html.erb
<div class="a5_container"> 

  <div class="pdf-title">
    PDFお支払い明細書
  </div>

  <div class="pdf-header">
    <div class="pdf-header-left">
      <div class="pdf-left-company">
        <div class="pdf-company-name">
          <%= @supplier.company %>
        </div>
        <div class="pdf-company-tag">
          御中
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu monthly-menu">
          対象期間
        </div>
        <div class="pdf-pay-text monthly-text">
          <%= @start_date %> ～ <%= @end_date %>
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu">
          支払い予定日
        </div>
        <div class="pdf-pay-text">
          <%= @pay_date %>
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu">
          合計金額
        </div>
        <div class="pdf-pay-text">
          <%= number_with_precision(@receipts.compact.sum { |r| r.total_price.to_f }, precision: 0) %>円
        </div>
      </div>
    </div>

    <div class="pdf-header-right">
      <div class="pdf-right-date">
        作成日：<%= Date.today %>
      </div>
      <div class="pdf-right-company">
        <%= @user.company %><br><br>
        住所：<%= @user.city %><%= @user.address %><br>
        電話番号：<%= @user.phone %><br>
        担当：<%= @user.manager %><br>
        登録番号：<%= @user.invoice %>
      </div>
    </div>
  </div>

  <div class="">
    <table class="pdf-table">
      <thead class="pdf-table-header">
        <tr>
          <th>取引日</th>
          <th>金額</th>
        </tr>
      </thead>
      <tbody>
        <% @receipts.each do |receipt| %>
        <tr>
          <td class="table-day"><%= receipt.transaction_date %></td>
          <td class="table-price"><%= receipt.total_price %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="back">
    <%= link_to '前のページに戻る', buys_order_index_path %>
  </div>
</div>

app/views/buys/receipt.pdf.erb
<html>
  <head>
    <meta charset="UTF-8">
      <style>
        @font-face { font-family: 'Noto Sans JP'; src: url('<%= asset_url("NotoSansJP-Regular.ttf") %>') format('truetype'); }
        body { font-family: 'Noto Sans JP', sans-serif; }
      </style>
  </head>
  <body>
    
    <div style="width: 600px;"> 

      <div style="text-align: center; font-size: 32px; margin-bottom: 32px;">
        支払い明細書
      </div>

      <table style="border-collapse: collapse; margin-bottom: 32px;">
        <tbody>
          <tr>
            <td style="width: 220px; border-bottom: 1px solid black; text-align: center; font-size: 24px;"><%= @supplier.company %></td>
            <td style="width: 40px; border-bottom: 1px solid black; font-size: 18px;">御中</td>
            <td style="width: 160px;"></td>
            <td style="text-align: right; font-size: 18px;">作成日：<%= Date.today %></td>
          </tr>
        </tbody>
      <table>

      <table style="border-collapse: collapse; margin-bottom: 32px;">
        <tbody>
          <tr>
            <td rowspan="2" style="width: 120px; border: 1px solid black; font-size: 18px; background-color: black; color: white; text-align: center;">対象期間</td>
            <td rowspan="2" style="width: 140px; border: 1px solid black; padding: 4px; text-align: center;"><%= @start_date %><br>～ <%= @end_date %></td>
            <td style="width: 120px;"></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td style="font-size: 20px;"><%= @user.company %></td>
          </tr>
          <tr>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; background-color: black; color: white; text-align: center;">振込予定日</td>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; text-align: center;"><%= @pay_date %></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td>住所：<%= @user.city %><%= @user.address %></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>電話番号：<%= @user.phone %></td>
          </tr>
          <tr>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; background-color: black; color: white; text-align: center;">合計金額</td>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; text-align: center;"><%= @receipts.sum(&:total_price) %>円</td>
            <td></td>
            <td>登録番号：<%= @user.invoice %></td>
          </tr>
          <tr>
            <td></td>
            <td>担当：<%= @user.manager %></td>
          </tr>
        </tbody>
      <table>

      <div style="margin: 0 auto;">
        <table style="border-collapse: collapse; width: 100%; margin: 0 auto;">
          <thead style="background-color: black; color: white;">
            <tr style="font-size: 18px; text-align: center;">
              <th style="width: 120px;">取引日</th>
              <th style="width: 180px;">金額</th>
              <th>備考</th>
            </tr>
          </thead>
          <tbody>
            <% @receipts.each do |receipt| %>
              <tr>
                <td style="border: 1px solid black; text-align: center; padding: 4px;"><%= receipt.transaction_date %></td>
                <td style="border: 1px solid black; text-align: right; padding: 4px;"><%= receipt.total_price %></td>
                <td style="border: 1px solid black; text-align: right; padding: 4px;"></td>
              </tr>
            <% end %>  
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/views/buys/search.html.erb
<div class="box_container">
  <div class="section-title">
    仕入れ先別の集計
  </div>
  <div class="box-center">
    <%= form_with url: buys_search_result_path, method: :get, local: true do %>
      <div class="box-wrap">
        <%= label_tag :supplier_id, "仕入れ先", class: "box-label" %><br>
        <%= select_tag :supplier_id, options_from_collection_for_select(@suppliers, :id, :company, params.fetch(:supplier_id, 1)), prompt: "仕入れ先を選択", required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :start_date, "開始日", class: "box-label" %><br>
        <%= date_field_tag :start_date, params[:start_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :end_date, "終了日", class: "box-label" %><br>
        <%= date_field_tag :end_date, params[:end_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap-btn">
        <%= submit_tag "検索", class: "box-content" %>
      </div>
    <% end %>


    <div class="back">
      <%= link_to  '前のページに戻る', root_path %>
    </div>
  </div>
</div>

app/views/buys/search_result.html.erb
<div class="table_container">
  <div class="section-title">
    仕入れ先別の集計
  </div>

  <div class="sub-title">
    <%= @supplier.company %>からの仕入れ<br>
    <%= @start_date %> ～ <%= @end_date %>
  </div>

  <table class="table-bordered">
    <thead>
      <tr>
        <th>日付</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody>
      <% @receipts.each do |receipt| %>
        <tr>
          <td class="table-day"><%= receipt.transaction_date %></td>
          <td class="table-price"><%= receipt.total_price %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <td class="table-total-text">合計</td>
      <td class="table-price"><%= number_with_precision(@receipts.compact.sum { |r| r.total_price.to_f }, precision: 0) %></td>
    </tfoot>
  </table>

  <div class="back">
    <%= link_to  '前のページに戻る', buys_search_path %>
  </div>
</div>

app/views/buys/show.html.erb
<div class="a5_container"> 

  <div class="pdf-title">
    発注書
  </div>

  <div class="pdf-header">
    <div class="pdf-header-left">
      <div class="pdf-left-company">
        <div class="pdf-company-name">
          <%= @supplier.company %>
        </div>
        <div class="pdf-company-tag">
          御中
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu">
          納品希望日
        </div>
        <div class="pdf-pay-text">
          <%= @buy.transaction_date %>
        </div>
      </div>
    </div>

    <div class="pdf-header-right">
      <div class="pdf-right-date">
        作成日：<%= Date.today %>
      </div>
      <div class="pdf-right-company">
        <%= @user.company %><br><br>
        住所：<%= @user.city %><%= @user.address %><br>
        電話番号：<%= @user.phone %><br>
        担当：<%= @user.manager %>
      </div>
    </div>
  </div>

  <div class="">
    <table class="pdf-table">
      <thead class="pdf-table-header">
        <tr>
          <th>商品名</th>
          <th>数量</th>
          <th>単位</th>
        </tr>
      </thead>
      <tbody>
        <% @buy.buy_items.each do |buy_item| %>
          <tr>
            <td><%= @items.find { |item| item.id == buy_item.item_id }&.item_name || "不明" %></td>
            <td class="pdf-table-quantity"><%= buy_item.quantity %></td>
            <td class="pdf-table-unit"><%= @items.find { |item| item.id == buy_item.item_id }&.unit || "不明" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="back">
    <%= link_to '前のページに戻る', buys_order_index_path %>
  </div>

app/views/buys/show.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <style>
        @font-face { font-family: 'Noto Sans JP'; src: url('<%= asset_url("NotoSansJP-Regular.ttf") %>') format('truetype'); }
        body { font-family: 'Noto Sans JP', sans-serif; }
      </style>
  </head>
  <body>

    <div style="width: 600px;"> 

      <div style="text-align: center; font-size: 32px; margin-bottom: 32px;">
        発注書
      </div>

      <table style="border-collapse: collapse; margin-bottom: 32px;">
        <tbody>
          <tr>
            <td style="width: 220px; border-bottom: 1px solid black; text-align: center; font-size: 24px;"><%= @supplier.company %></td>
            <td style="width: 40px; border-bottom: 1px solid black; font-size: 18px;">御中</td>
            <td style="width: 160px;"></td>
            <td style="text-align: right; font-size: 18px;">作成日：<%= Date.today %></td>
          </tr>
        </tbody>
      <table>

      <table style="border-collapse: collapse; margin-bottom: 32px;">
        <tbody>
          <tr>
            <td style="width: 120px;"></td>
            <td style="width: 140px;"></td>
            <td style="width: 120px;"></td>
            <td style="font-size: 20px;"><%= @user.company %></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>住所：<%= @user.city %><%= @user.address %></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>電話番号：<%= @user.phone %></td>
          </tr>
          <tr>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; background-color: black; color: white; text-align: center;">納品希望日</td>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; text-align: center;"><%= @buy.transaction_date %></td>
            <td></td>
            <td>登録番号：<%= @user.invoice %></td>
          </tr>
          <tr>
            <td></td>
            <td>担当：<%= @user.manager %></td>
          </tr>
        </tbody>
      <table>

      <div style="margin: 0 auto;">
        <table style="border-collapse: collapse; width: 100%; margin: 0 auto;">
          <thead style="background-color: black; color: white;">
            <tr style="font-size: 20px;">
              <th style="border: 1px solid black; padding: 4px;">商品名</th>
              <th style="width: 64px; border: 1px solid black; padding: 4px;">数量</th>
              <th style="width: 64px; border: 1px solid black; padding: 4px;">単位</th>
            </tr>
          </thead>
          <tbody>
            <% @buy.buy_items.each do |buy_item| %>
              <tr style="font-size: 20px;">
                <td style="border: 1px solid black; padding: 4px;"><%= @items.find { |item| item.id == buy_item.item_id }&.item_name || "不明" %></td>
                <td style="border: 1px solid black; text-align: center; padding: 4px;"><%= buy_item.quantity %></td>
                <td style="border: 1px solid black; text-align: center; padding: 4px;"><%= @items.find { |item| item.id == buy_item.item_id }&.unit || "不明" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>