config/routes.rb
Rails.application.routes.draw do

  root "shops#index"

  get 'shops/index'
  get 'suppliers/order_index', to: 'suppliers#order_index'
  get 'buys/order_index', to: 'buys#order_index'
  get 'buys/search', to: 'buys#search'
  get 'buys/search_result', to: 'buys#search_result'
  get 'buys/issue_receipt', to: 'buys#issue_receipt'
  get 'buys/receipt', to: 'buys#receipt'
  get 'customers/order_index', to: 'customers#order_index'
  get 'sells/order_index', to: 'sells#order_index'
  get 'sells/search', to: 'sells#search'
  get 'sells/search_result', to: 'sells#search_result'
  get 'sells/issue_receipt', to: 'sells#issue_receipt'
  get 'sells/receipt', to: 'sells#receipt'
  get 'items/search', to: 'items#search'
  get 'items/buy_receipt', to: 'items#buy_receipt'
  get 'items/sell_receipt', to: 'items#sell_receipt'
  get 'categories/search', to: 'categories#search'
  get 'categories/buy_receipt', to: 'categories#buy_receipt'
  get 'categories/sell_receipt', to: 'categories#sell_receipt'


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: :show

  resources :categories do
    get 'items', to: 'categories#items'
    collection do
      post 'import', to: 'categories#import'
    end
  end

  resources :items do
    member do
      get 'details'
    end
    collection do
      post 'import'
    end
  end
  resources :suppliers do
    collection do
      post 'import'
    end
    resources :buys do
    end
  end
  resources :customers do
    collection do
      post 'import'
    end
    resources :sells do
    end
  end
end

app/models/category.rb
require 'csv'

class Category < ApplicationRecord
  validates :category, presence: true

  belongs_to :user
  has_many :items
  has_many :buy_items
  has_many :sell_items

  def self.import_from_csv(file, current_user)
    CSV.foreach(file.path, headers: true) do |row|
      category_attributes = row.to_hash
      cleaned_attributes = category_attributes.transform_keys { |key| key.strip.gsub("\uFEFF", '') }
  
      user = current_user
      if user
        cleaned_attributes["user_id"] = user.id
      end
  
      cleaned_attributes.delete("user_name")
      cleaned_attributes.delete("user_email")
      cleaned_attributes.delete_if { |key, value| key.blank? }
  
      Category.create!(cleaned_attributes)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories.order("categories.category ASC")
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to new_category_path
    else
      render :new
    end
  end

  def edit
    @category = current_user.categories.find(params[:id])
  end

  def update
    @category = current_user.categories.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    category = current_user.categories.find(params[:id])
    category.destroy
    redirect_to categories_path
  end

  def items
    @items = current_user.items.where(category_id: params[:category_id])
    render json: { items: @items }
  end

  def import
    def import
      Category.import_from_csv(params[:file], current_user)
      redirect_to categories_path
    end
  end

  def search
    @categories = current_user.categories
  end

  def buy_receipt
    @category_id = params[:category_id]
    @category = current_user.categories.find(@category_id)
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @buy_receipts = current_user.buys.joins(buy_items: :item)
                                    .where(items: { category_id: @category_id })
                                    .where("transaction_date >= ?", @start_date)
                                    .where("transaction_date <= ?", @end_date)
                                    .order("buys.transaction_date ASC")
                                    .distinct
  end

  def sell_receipt
    @category_id = params[:category_id]
    @category = current_user.categories.find(@category_id)
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @sell_receipts = current_user.sells.joins(sell_items: :item)
                        .where(items: { category_id: @category_id })
                        .where("transaction_date >= ?", @start_date)
                        .where("transaction_date <= ?", @end_date)
                        .order("sells.transaction_date ASC")
                        .distinct
  end

  private
  def category_params
    params.require(:category).permit(:category)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/buy_receipt.html.erb
<div class="table_container">
  <div class="section-title">
    カテゴリ別集計（仕入れ）
  </div>

  <div class="sub-title">
    カテゴリ：<%= @category.category %><br>
    <%= @start_date %>  ～  <%= @end_date %>
  </div>

  <table class="table-bordered">
    <thead>
      <tr>
        <th>日付</th>
        <th>仕入れ先</th>
        <th>商品名</th>
        <th>数量</th>
        <th>単位</th>
        <th>単価</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody>
      <% total = 0 %>
      <% @buy_receipts.each do |buy_receipt| %>
        <% buy_receipt.buy_items.each do |buy_item| %>
          <% if buy_item.item.category_id == @category_id.to_i %>
            <tr>
              <td class="table-day"><%= buy_receipt.transaction_date %></td>
              <td><%= buy_receipt.supplier.company %>
              <td><%= buy_item.item.item_name %></td>
              <td class="table-quantity"><%= buy_item.quantity %></td>
              <td class="table-unit"><%= buy_item.item.unit %></td>
              <td class="table-price"><%= buy_item.item_price %></td>
              <td class="table-price"><%= buy_item.item_total_price %></td>
            </tr>
            <% total += buy_item.item_total_price unless buy_item.item_total_price.nil? %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td class="table-total-text">合計</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="table-price"><%= total %></td>
      </tr>
    </tfoot>
  </table>

  <div class="back">
    <%= link_to  '前のページに戻る', categories_search_path %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="input_container">
  <div class="section-title">
    カテゴリの編集
  </div>

  <%= form_with model: @category, local: true do |f| %>

    <div>
      <%= f.label :category, 'カテゴリ名', class: "foorm_wrap_text" %>
      <span class="attension">必須</span><br>
      <%= f.text_field :category, class: "form_wrap_field" %>
    </div>
    <div class="btn_wrap">
      <%= f.submit "更新", class: "form_btn" %>
    </div>
  <% end %>

  <div class="back">
    <%= link_to  '前のページに戻る', categories_path %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="table_container">
  <div class="section-title">
    カテゴリ一覧
  </div>

  <table class="table-bordered">
    <thead>
      <tr>
        <th>カテゴリー</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td class="table-name"><%= category.category %></td>
          <td class="table-link"><%= link_to '編集', edit_category_path(category.id) %></td>
          <td class="table-link"><%= link_to '削除', category_path(category.id), data: { turbo_method: :delete, confirm: '削除してもよろしいですか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="back">
    <%= link_to  '前のページに戻る', root_path %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="input_container">
  <div class="section-title">
    カテゴリの登録
  </div>

  <div class="sub-title">
    <input type="radio" id="input-registration-radio" name="registration-method" value="input" checked>
    <label for="input-registration-radio">直接入力で登録</label>
    <input type="radio" id="csv-registration-radio" name="registration-method" value="csv">
    <label for="csv-registration-radio">CSVで登録</label>
  </div>

  <div id="input-registration" class="input-registration">
    <%= form_with model: @category, local: true do |f| %>
      <div>
        <%= f.label :category, 'カテゴリ名', class: "form_wrap_text" %>
        <span class="attension">必須</span><br>
        <%= f.text_field :category, class: "form_wrap_field" %>
      </div>
      <div class="btn_wrap">
        <%= f.submit "登録", class: "form_btn" %>
      </div>
    <% end %>
  </div>

  <div id="csv-registration" class="csv-registration">
    <%= form_with(url: import_categories_path, local: true, multipart: true) do |form| %>
      <div class="form-group">
        <%= form.file_field :file, required: true %>
      </div>
      <div class="actions">
        <%= form.submit "インポート" %>
      </div>
    <% end %>
  </div>

  <div class="back">
    <%= link_to  '前のページに戻る', root_path %>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', (event) => {
    const inputRadio = document.getElementById('input-registration-radio');
    const csvRadio = document.getElementById('csv-registration-radio');
    const inputSection = document.getElementById('input-registration');
    const csvSection = document.getElementById('csv-registration');

    // Function to toggle visibility
    function toggleSections() {
      if (inputRadio.checked) {
        inputSection.style.display = 'block';
        csvSection.style.display = 'none';
      } else if (csvRadio.checked) {
        inputSection.style.display = 'none';
        csvSection.style.display = 'block';
      }
    }

    // Event listeners for radio buttons
    inputRadio.addEventListener('change', toggleSections);
    csvRadio.addEventListener('change', toggleSections);

    // Initial visibility
    toggleSections();
  });
</script>

app/views/categories/search.erb
<div class="box_container">
  <div class="section-title">
    カテゴリ別の集計
  </div>

  <div class="box-center">
    <div class="sub-title">
      <span class="attension">選択</span><br>
      <label for="search-switch"></label>
      <input type="radio" id="buy-search-radio" name="search-switch" value="buy" checked>
      <label for="buy-search-radio">仕入れ</label>
      <input type="radio" id="sell-search-radio" name="search-switch" value="sell">
      <label for="sell-search-radio">販売</label>
    </div>

    <div id="buy-search" class="buy-search">
      <%= form_with url: categories_buy_receipt_path, method: :get, local: true do %>
        <div class="box-wrap">
          <%= label_tag :category_id, "カテゴリ", class: "box-label" %><br>
          <%= select_tag :category_id, options_from_collection_for_select(@categories, :id, :category, params[:category_id]), prompt: "カテゴリを選択", class: "box-content" %>
        </div>

        <div class="box-wrap">
          <%= label_tag :start_date, "開始日", class: "box-label" %><br>
          <%= date_field_tag :start_date, params[:start_date], class: "box-content" %>
        </div>

        <div class="box-wrap">
          <%= label_tag :end_date, "終了日", class: "box-label" %><br>
          <%= date_field_tag :end_date, params[:end_date], class: "box-content" %>
        </div>

        <div class="box-wrap-btn">
          <%= submit_tag "仕入れを検索", class: "box-content" %>
        </div>
      <% end %>
    </div>

    <div id="sell-search" class="sell-search">
      <%= form_with url: categories_sell_receipt_path, method: :get, local: true do %>
        <div class="box-wrap">
          <%= label_tag :category_id, "カテゴリ", class: "box-label" %><br>
          <%= select_tag :category_id, options_from_collection_for_select(@categories, :id, :category, params[:category_id]), prompt: "カテゴリを選択", class: "box-content" %>
        </div>

        <div class="box-wrap">
          <%= label_tag :start_date, "開始日", class: "box-label" %><br>
          <%= date_field_tag :start_date, params[:start_date], class: "box-content" %>
        </div>

        <div class="box-wrap">
          <%= label_tag :end_date, "終了日", class: "box-label" %><br>
          <%= date_field_tag :end_date, params[:end_date], class: "box-content" %>
        </div>

        <div class="box-wrap-btn">
          <%= submit_tag "販売を検索", class: "box-content" %>
        </div>
      <% end %>
    </div>

    <div class="back">
      <%= link_to  '前のページに戻る', root_path %>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', (event) => {
    const buyRadio = document.getElementById('buy-search-radio');
    const sellRadio = document.getElementById('sell-search-radio');
    const buySearchSection = document.getElementById('buy-search');
    const sellSearchSection = document.getElementById('sell-search');

    // 初期表示はbuy-searchを表示
    buySearchSection.style.display = 'block';
    sellSearchSection.style.display = 'none';

    const toggleSections = () => {
      if (buyRadio.checked) {
        buySearchSection.style.display = 'block';
        sellSearchSection.style.display = 'none';
      } else if (sellRadio.checked) {
        buySearchSection.style.display = 'none';
        sellSearchSection.style.display = 'block';
      }
    };

    // ラジオボタンの変更イベントにリスナーを追加
    buyRadio.addEventListener('change', toggleSections);
    sellRadio.addEventListener('change', toggleSections);
  });
</script>

app/views/categories/sell_receipt.html.erb
<div class="table_container">
  <div class="section-title">
    販売カテゴリ別の集計
  </div>

  <div class="sub-title">
    カテゴリ：<%= @category.category %><br>
    <%= @start_date %>～<%= @end_date %>
  </div>

  <table class="table-bordered">
    <thead>
      <tr>
        <th>日付</th>
        <th>得意先</th>
        <th>商品名</th>
        <th>数量</th>
        <th>単位</th>
        <th>単価</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody>
      <% total = 0 %>
      <% @sell_receipts.each do |sell_receipt| %>
        <% sell_receipt.sell_items.each do |sell_item| %>
          <% if sell_item.item.category_id == @category_id.to_i %>
            <tr>
              <td class="table-day"><%= sell_receipt.transaction_date %></td>
              <td><%= sell_receipt.customer.company %></td>
              <td><%= sell_item.item.item_name %></td>
              <td class="table-quantity"><%= sell_item.quantity %></td>
              <td class="table-unit"><%= sell_item.item.unit %></td>
              <td class="table-price"><%= sell_item.item_price %></td>
              <td class="table-price"><%= sell_item.item_total_price %></td>
            </tr>
            <% total += sell_item.item_total_price %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td class="table-total-text">合計</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="table-price"><%= total %></td>
      </tr>
    </tfoot>
  </table>

  <div class="back">
    <%= link_to  '前のページに戻る', categories_search_path %>
  </div>
</div>