config/routes.rb
Rails.application.routes.draw do

  root "shops#index"

  get 'shops/index'
  get 'suppliers/order_index', to: 'suppliers#order_index'
  get 'buys/order_index', to: 'buys#order_index'
  get 'buys/search', to: 'buys#search'
  get 'buys/search_result', to: 'buys#search_result'
  get 'buys/issue_receipt', to: 'buys#issue_receipt'
  get 'buys/receipt', to: 'buys#receipt'
  get 'customers/order_index', to: 'customers#order_index'
  get 'sells/order_index', to: 'sells#order_index'
  get 'sells/search', to: 'sells#search'
  get 'sells/search_result', to: 'sells#search_result'
  get 'sells/issue_receipt', to: 'sells#issue_receipt'
  get 'sells/receipt', to: 'sells#receipt'
  get 'items/search', to: 'items#search'
  get 'items/buy_receipt', to: 'items#buy_receipt'
  get 'items/sell_receipt', to: 'items#sell_receipt'
  get 'categories/search', to: 'categories#search'
  get 'categories/buy_receipt', to: 'categories#buy_receipt'
  get 'categories/sell_receipt', to: 'categories#sell_receipt'


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: :show

  resources :categories do
    get 'items', to: 'categories#items'
    collection do
      post 'import', to: 'categories#import'
    end
  end

  resources :items do
    member do
      get 'details'
    end
    collection do
      post 'import'
    end
  end
  resources :suppliers do
    collection do
      post 'import'
    end
    resources :buys do
    end
  end
  resources :customers do
    collection do
      post 'import'
    end
    resources :sells do
    end
  end
end

app/models/sell.rb
class Sell < ApplicationRecord
  validates :transaction_date, presence: true
  validates :total_price, presence: true

  belongs_to :user
  belongs_to :customer
  has_many :sell_items, inverse_of: :sell, dependent: :destroy
  has_many :sells, through: :sell_items

  accepts_nested_attributes_for :sell_items, allow_destroy: true
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  def order_index
    @sells = current_user.sells.order("sells.transaction_date DESC")
                               .page(params[:page]).per(20)
  end

  def new
    @customer = current_user.customers.find(params[:customer_id])
    @sell = current_user.sells.new
    @sell.sell_items.build
    @items = current_user.items
    @categories = current_user.categories
  end

  def create
    @customer = current_user.customers.find(params[:customer_id])
    @sell = current_user.sells.new(sell_params.merge(customer_id: @customer.id))
    @categories = current_user.categories
    if @sell.save
      redirect_to root_path
    else
      @items = current_user.items
      @categories = current_user.categories
      render :new
    end
  end

  def edit
    @sell = current_user.sells.find(params[:id])
    @customer = @sell.customer
    @categories = current_user.categories
    @items = current_user.items
  end

  def update
    @sell = current_user.sells.find(params[:id])
    @customer = @sell.customer
    @categories = current_user.categories
    @items = current_user.items
    if @sell.update(sell_params)
      redirect_to sells_order_index_path
    else
      render :edit
    end
  end

  def destroy
    sell = current_user.sells.find(params[:id])
    sell.destroy
    redirect_to sells_order_index_path
  end

  def search
    @customers = current_user.customers.order("customers.company ASC")
  end

  def search_result
    @customer_id = params[:customer_id]
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @customer = current_user.customers.find(@customer_id)

    @receipts = current_user.sells.where(customer_id: @customer_id)
                                  .where("transaction_date >= ?", @start_date)
                                  .where("transaction_date <= ?", @end_date)
                                  .order("sells.transaction_date ASC")
                                  .distinct
  end

  def issue_receipt
    @customers = current_user.customers.order("customers.company ASC")
  end

  def receipt
    @user = current_user
    @customer_id = params[:customer_id]
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @pay_date = params[:pay_date]
    @customer = current_user.customers.find(@customer_id)

    @receipts = current_user.sells.where(customer_id: @customer_id)
                                  .where("transaction_date >= ?", @start_date)
                                  .where("transaction_date <= ?", @end_date)
                                  .order("sells.transaction_date ASC")
                                  .distinct
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'receipt', # 出力されるPDFのファイル名
               template: 'sells/receipt', # テンプレートファイルの指定
               enable_local_file_access: true, # ローカルファイルの読み込みを許可
               enable_internal_file_access: true,
               page_size: 'A5'
               #  orientation: 'Landscape'    # 横向きに設定
      end
    end
  end

  def show
    @user = current_user
    @sell = current_user.sells.find(params[:id])
    @customer = @sell.customer
    @categories = current_user.categories
    @items = current_user.items
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'show', # 出力されるPDFのファイル名
               template: 'sells/show', # テンプレートファイルの指定
               enable_local_file_access: true, # ローカルファイルの読み込みを許可
               enable_internal_file_access: true,
               page_size: 'A5'
               #  orientation: 'Landscape'    # 横向きに設定
      end
    end
  end

  private 
  def sell_params
    params.require(:sell).permit(:transaction_date, :total_price, sell_items_attributes: [:id, :item_price, :item_total_price, :quantity, :category_id, :item_id, :destroy])
                         .merge(user_id: current_user.id)
  end
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/sells/edit.html.erb
<div class="table_container">
  <div class="section-title">
    納品履歴の編集
  </div>

  <div class="sub-title">
    <%= @customer.company %>への納品
  </div>

  <%= form_with(model: [@customer, @sell], local: true) do |f| %>
    <div>
      <%= f.label :transaction_date, "納品日" %>
      <%= f.date_field :transaction_date, class: "form-group" %>
    </div>

    <table class="table-bordered">
      <thead>
        <tr>
          <th>カテゴリ</th>
          <th>商品</th>
          <th>数量</th>
          <th>単位</th>
          <th>単価</th>
          <th>金額</th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :sell_items do |sell_item_form| %>
          <tr>
            <td><%= sell_item_form.collection_select :category_id, @categories, :id, :category, { prompt: "カテゴリを選択" }, { class: "" } %></td>
            <td><%= sell_item_form.collection_select :item_id, @items, :id, :item_name, { prompt: "商品を選択" }, { class: "" } %></td>
            <td><%= sell_item_form.number_field :quantity, class: 'quantity-edit table-quantity', 'data-id': sell_item_form.index %></td>
            <td class="table-unit" id="unit"><%= @items.find { |item| item.id == sell_item_form.object.item_id }&.unit || "--" %></td>
            <td><%= sell_item_form.text_field :item_price, class: 'item-price-edit table-price', 'data-id': sell_item_form.index %></td>
            <td><%= sell_item_form.text_field :item_total_price, class: 'item-total-price-edit table-price', 'data-id': sell_item_form.index %></td>
          </tr>
        <% end %>  
      </tbody>
      <tfoot>
        <td class="table-total-text"><%= f.label :total_price, '合計' %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= f.text_field :total_price, id: 'total_price_edit', class: 'table-price' %></td>
      </tfoot>
    </table>

    <div class="box-wrap-btn">
      <%= f.submit "更新", class: "box-content" %>
    </div>
  <% end %>

  <div class="back">
    <%= link_to  '前のページに戻る', sells_order_index_path %>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {

    // すべての quantity フィールドにイベントリスナーを追加
    document.querySelectorAll('.quantity-edit').forEach(input => {
      input.addEventListener('input', updateItemTotalPriceFromQuantity);
    });

    // すべての item_price フィールドにイベントリスナーを追加
    document.querySelectorAll('.item-price-edit').forEach(input => {
      input.addEventListener('input', updateItemTotalPriceFromPrice);
    });

    // すべての item_total_price フィールドにイベントリスナーを追加
    document.querySelectorAll('.item-total-price-edit').forEach(input => {
      input.addEventListener('input', updateTotalPrice);
    });

    function updateItemTotalPriceFromQuantity(event) {
      const input = event.target;
      const index = input.dataset.id;
      const itemPriceInput = document.querySelector(`.item-price-edit[data-id="${index}"]`);
      const itemTotalPriceInput = document.querySelector(`.item-total-price-edit[data-id="${index}"]`);
      const quantity = parseInt(input.value || 0, 10);
      const itemPrice = parseInt(itemPriceInput.value || 0, 10);

      // item_total_priceを計算し設定
      const itemTotalPrice = quantity * itemPrice;
      itemTotalPriceInput.value = itemTotalPrice;

      // 合計価格を更新
      updateTotalPrice();
    }

    function updateItemTotalPriceFromPrice(event) {
      const input = event.target;
      const index = input.dataset.id;
      const quantityInput = document.querySelector(`.quantity-edit[data-id="${index}"]`);
      const itemTotalPriceInput = document.querySelector(`.item-total-price-edit[data-id="${index}"]`);
      const quantity = parseInt(quantityInput.value || 0, 10);
      const itemPrice = parseInt(input.value || 0, 10);

      // item_total_priceを計算し設定
      const itemTotalPrice = quantity * itemPrice;
      itemTotalPriceInput.value = itemTotalPrice;

      // 合計価格を更新
      updateTotalPrice();
    }

    function updateTotalPrice() {
      // すべての item_total_price を合計し設定
      const total = Array.from(document.querySelectorAll('.item-total-price-edit')).reduce((sum, input) => {
        return sum + parseInt(input.value || 0, 10);
      }, 0);

      document.getElementById('total_price_edit').value = total;
    }

  });
</script>

app/views/sells/issue_receipt.html.erb
<div class="box_container">
  <div class="section-title">
    請求書の作成
  </div>
  <div class="box-center">
    <%= form_with url: sells_receipt_path(format: :pdf), method: :get, html: { target: '_blank' }, local: true do %>
      <div class="box-wrap">
        <%= label_tag :customer_id, "得意先", class: "box-label" %><br>
        <%= select_tag :customer_id, options_from_collection_for_select(@customers, :id, :company, params.fetch(:customer_id, 1)), prompt: "得意先を選択", required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :start_date, "開始日", class: "box-label" %><br>
        <%= date_field_tag :start_date, params[:start_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :end_date, "終了日", class: "box-label" %><br>
        <%= date_field_tag :end_date, params[:end_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :end_date, "支払い期日", class: "box-label" %><br>
        <%= date_field_tag :pay_date, params[:pay_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap-btn">
        <%= submit_tag "作成", class: "box-content" %>
      </div>
    <% end %>
  </div>

  <div class="back", style="text-align:center">
    <%= link_to  '前のページに戻る', root_path %>
  </div>
</div>

app/views/sells/new.html.erb
<div class="table_container">
  <div class="section-title">
    <%= @customer.company %>への納品書
  </div>

  <%= form_with(model: [@customer, @sell]) do |f| %>
    <div>
      <%= f.label :transaction_date, "納品日" %>
      <%= f.date_field :transaction_date, class: "form-group" %>
    </div>

    <table class="table-bordered">
      <thead>
        <tr>
          <th>カテゴリ</th>
          <th>商品</th>
          <th>数量</th>
          <th>単位</th>
          <th>単価</th>
          <th>合計</th>
        </tr>
      </thead>
      <tbody id="sell-item-forms">
        <%= f.fields_for :sell_items do |sell_item_form| %>
          <tr class="sell-item">
            <td><%= sell_item_form.collection_select :category_id, @categories, :id, :category, { prompt: "カテゴリを選択" }, { class: "sell-category-select" } %></td>
            <td><%= sell_item_form.collection_select :item_id, [], :id, :item_name, { prompt: "商品を選択" }, { class: "sell-item-select" } %></td>
            <td class="table-quantity"><%= sell_item_form.number_field :quantity, class: 'quantity-input' %></td>
            <td class="table-unit" id="unit">--</td>
            <td class="table-price"><%= sell_item_form.text_field :item_price, class: 'item-price' %></td>
            <td class="table-price"><%= sell_item_form.text_field :item_total_price, class: 'item-total-price' %></td>
          </tr>
        <% end %>  
      </tbody>
      <tfoot>
        <td class="table-total-text"><%= f.label :total_price, '総計' %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="table-price"><%= f.text_field :total_price %></td>
      </tfoot>
    </table>

    <%# 追加ボタン %>
    <button type="button" id="add-form-set" class="add-form">商品を追加</button>

    <div class="box-wrap-btn">
      <%= f.submit "作成", class: "box-content" %>
    </div>
  <% end %>

  <div class="back">
  <%= link_to '前のページに戻る', suppliers_order_index_path %>
  </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
    // 初期化
    initializeEvents();

    // フィールドセットを追加するボタンのイベント
    document.getElementById('add-form-set').addEventListener('click', function () {
      addNewFields();
    });

    // 合計価格を更新する関数
    function updateTotalPrice() {
      let totalPrice = 0;
      document.querySelectorAll('.sell-item').forEach(sellItem => {
        const itemTotalPriceInput = sellItem.querySelector('.item-total-price');
        const itemTotalPrice = parseFloat(itemTotalPriceInput.value) || 0;
        totalPrice += itemTotalPrice;
      });
      document.querySelector('input[name="sell[total_price]"]').value = totalPrice;
    }

    // イベント初期化の関数
    function initializeEvents() {
      document.querySelectorAll('.sell-category-select').forEach(categorySelect => {
        categorySelect.addEventListener('change', event => {
          const categoryId = event.target.value;
          const sellItem = event.target.closest('.sell-item');
          const itemSelect = sellItem.querySelector('.sell-item-select');
          const unitSpan = sellItem.querySelector('.table-unit');
          const itemPriceInput = sellItem.querySelector('.item-price');
          const itemTotalPriceInput = sellItem.querySelector('.item-total-price');
          const quantityInput = sellItem.querySelector('.quantity-input');

          itemSelect.innerHTML = '<option value="">商品を選択</option>';
          itemPriceInput.value = '';
          unitSpan.textContent = '--';
          itemTotalPriceInput.value = '';
          quantityInput.value = '';
          updateTotalPrice(); // 合計価格を更新

          if (categoryId) {
            fetch(`/categories/${categoryId}/items`)
              .then(response => response.json())
              .then(data => {
                data.items.forEach(item => {
                  const option = document.createElement('option');
                  option.value = item.id;
                  option.textContent = item.item_name;
                  itemSelect.appendChild(option);
                });
              })
              .catch(error => console.error('Error fetching items:', error));
          }
        });
      });

      document.querySelectorAll('.sell-item-select').forEach(itemSelect => {
        itemSelect.addEventListener('change', event => {
          const itemId = event.target.value;
          const sellItem = event.target.closest('.sell-item');
          const itemPriceInput = sellItem.querySelector('.item-price');
          const unitSpan = sellItem.querySelector('.table-unit');
          const itemTotalPriceInput = sellItem.querySelector('.item-total-price');
          const quantityInput = sellItem.querySelector('.quantity-input');
          let itemPrice = 0;

          itemPriceInput.value = ''; // リセット
          unitSpan.textContent = '--';
          itemTotalPriceInput.value = ''; // リセット
          quantityInput.value = '';
          updateTotalPrice(); // 合計価格を更新

          if (itemId) {
            fetch(`/items/${itemId}/details`)
              .then(response => response.json())
              .then(data => {
                itemPrice = data.price;
                unitSpan.textContent = data.unit;
                itemPriceInput.value = itemPrice;
                updateItemTotalPrice(sellItem, itemPrice);
              })
              .catch(error => console.error('Error fetching item details:', error));
          }
        });
      });

      document.querySelectorAll('.quantity-input').forEach(quantityInput => {
        quantityInput.addEventListener('input', event => {
          const sellItem = event.target.closest('.sell-item');
          const itemPrice = parseFloat(sellItem.querySelector('.item-price').value) || 0;
          updateItemTotalPrice(sellItem, itemPrice);
        });
      });

      // item-price に対してもイベントリスナーを追加
      document.querySelectorAll('.item-price').forEach(itemPriceInput => {
        itemPriceInput.addEventListener('input', event => {
          const sellItem = event.target.closest('.sell-item');
          const itemPrice = parseFloat(itemPriceInput.value) || 0;
          updateItemTotalPrice(sellItem, itemPrice);
        });
      });
    }

    // フィールドセット追加
    function addNewFields() {
      const existingSellItems = document.querySelectorAll('.sell-item');
      const newFields = existingSellItems[0].cloneNode(true);
      const newIndex = existingSellItems.length;

      newFields.querySelectorAll('input, select').forEach(input => {
        const name = input.getAttribute('name').replace(/\d+/, newIndex);
        const id = input.getAttribute('id').replace(/\d+/, newIndex);
        input.setAttribute('name', name);
        input.setAttribute('id', id);
        input.value = '';
      });

      newFields.querySelector('.table-unit').textContent = '--';
      document.getElementById('sell-item-forms').appendChild(newFields);
      initializeEvents();
    }

    // アイテムの合計価格を更新
    function updateItemTotalPrice(sellItem, itemPrice) {
      const quantityInput = sellItem.querySelector('.quantity-input');
      const itemTotalPriceInput = sellItem.querySelector('.item-total-price');
      const quantity = parseFloat(quantityInput.value) || 0;
      itemTotalPriceInput.value = (itemPrice * quantity);
      updateTotalPrice(); // 合計価格を更新
    }
  });
</script>

app/views/sells/order_index.html.erb
<div class="table_container">
  <div class="section-title">
    納品履歴
  </div>

  <table class="table-bordered">
    <thead>
      <tr>
        <th>納品日</th>
        <th>発注先</th>
        <th>金額</th>
        <th>編集</th>
        <th>削除</th>
        <th>印刷</th>
      </tr>
    </thead>
    <tbody>
      <% @sells.each do |sell| %>
        <tr>
          <td class="table-day"><%= sell.transaction_date %></td>
          <td class="table-name"><%= sell.customer.company %></td>
          <td class="table-price"><%= sell.total_price %></td>
          <td class="table-link"><%= link_to '編集', edit_customer_sell_path(customer_id: sell.customer_id, id: sell.id) %></td>
          <td class="table-link"><%= link_to '削除', customer_sell_path(customer_id: sell.customer_id, id: sell.id), method: :delete, data: { confirm: '削除してもよろしいですか？' } %></td>
          <td class="table-link"><%= link_to '印刷', customer_sell_path(customer_id: sell.customer_id, id: sell.id, format: :pdf), target: '_blank' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @sells %>

  <div class="back">
    <%= link_to  '前のページに戻る', root_path %>
  </div>
</div>

app/views/sells/receipt.html.erb
<div class="a5_container"> 

  <div class="pdf-title">
    PDF請求書
  </div>

  <div class="pdf-header">
    <div class="pdf-header-left">
      <div class="pdf-left-company">
        <div class="pdf-company-name">
          <%= @customer.company %>
        </div>
        <div class="pdf-company-tag">
          御中
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu monthly-menu">
          対象期間
        </div>
        <div class="pdf-pay-text monthly-text">
          <%= @start_date %> ～ <%= @end_date %>
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu">
          お支払い期日
        </div>
        <div class="pdf-pay-text">
          <%= @pay_date %>
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu">
          合計金額
        </div>
        <div class="pdf-pay-text">
          <%= @receipts.sum(&:total_price) %>円
        </div>
      </div>
    </div>

    <div class="pdf-header-right">
      <div class="pdf-right-date">
        作成日：<%= Date.today %>
      </div>
      <div class="pdf-right-company">
        <%= @user.company %><br><br>
        住所：<%= @user.city %><%= @user.address %><br>
        電話番号：<%= @user.phone %><br>
        担当：<%= @user.manager %><br>
        登録番号：<%= @user.invoice %>
      </div>
    </div>
  </div>

  <div class="">
    <table class="pdf-table">
      <thead class="pdf-table-header">
        <tr>
          <th>取引日</th>
          <th>金額</th>
        </tr>
      </thead>
      <tbody>
        <% @receipts.each do |receipt| %>
          <tr>
            <td class="table-day"><%= receipt.transaction_date %></td>
            <td class="table-price"><%= receipt.total_price %></td>
          </tr>
        <% end %>  
      </tbody>
    </table>
  </div>

  <div class="back">
    <%= link_to '前のページに戻る', sells_order_index_path %>
  </div>
</div>

app/views/sells/receipt.pdf.erb
<html>
  <head>
    <meta charset="UTF-8">
      <style>
        @font-face { font-family: 'Noto Sans JP'; src: url('<%= asset_url("NotoSansJP-Regular.ttf") %>') format('truetype'); }
        body { font-family: 'Noto Sans JP', sans-serif; }
      </style>
  </head>
  <body>
    <div style="width: 600px;"> 

      <div style="text-align: center; font-size: 32px; margin-bottom: 32px;">
        請求書
      </div>

      <table style="border-collapse: collapse; margin-bottom: 32px;">
        <tbody>
          <tr>
            <td style="width: 220px; border-bottom: 1px solid black; text-align: center; font-size: 24px;"><%= @customer.company %></td>
            <td style="width: 40px; border-bottom: 1px solid black; font-size: 18px;">御中</td>
            <td style="width: 160px;"></td>
            <td style="text-align: right; font-size: 18px;">作成日：<%= Date.today %></td>
          </tr>
        </tbody>
      <table>

      <table style="border-collapse: collapse; margin-bottom: 32px;">
        <tbody>
          <tr>
            <td rowspan="2" style="width: 120px; border: 1px solid black; font-size: 18px; background-color: black; color: white; text-align: center;">対象期間</td>
            <td rowspan="2" style="width: 140px; border: 1px solid black; padding: 4px; text-align: center;"><%= @start_date %><br>～ <%= @end_date %></td>
            <td style="width: 120px;"></td>
            <td style="font-size: 20px;"><%= @user.company %></td>
          </tr>
          <tr>
            <td></td>
            <td>住所：<%= @user.city %><%= @user.address %></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>電話番号：<%= @user.phone %></td>
          </tr>
          <tr>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; background-color: black; color: white; text-align: center;">合計金額</td>
            <td rowspan="2" style="border: 1px solid black; font-size: 18px; text-align: center;"><%= @receipts.sum(&:total_price) %>円</td>
            <td></td>
            <td>登録番号：<%= @user.invoice %></td>
          </tr>
          <tr>
            <td></td>
            <td>担当：<%= @user.manager %></td>
          </tr>
        </tbody>
      <table>

      <div style="margin: 0 auto;">
        <table style="border-collapse: collapse; width: 100%; margin: 0 auto;">
          <thead style="background-color: black; color: white;">
            <tr style="font-size: 18px; text-align: center;">
              <th style="width: 120px;">取引日</th>
              <th style="width: 180px;">金額</th>
              <th>備考</th>
            </tr>
          </thead>
          <tbody>
            <% @receipts.each do |receipt| %>
              <tr>
                <td style="border: 1px solid black; text-align: center; padding: 4px;"><%= receipt.transaction_date %></td>
                <td style="border: 1px solid black; text-align: right; padding: 4px;"><%= receipt.total_price %></td>
                <td style="border: 1px solid black; text-align: right; padding: 4px;"></td>
              </tr>
            <% end %>  
          </tbody>
        </table>
      </div>

      <div style="margin-top: 32px; border-top: 2px solid black; border-bottom: 2px solid black; padding: 16px;">
        <div style="">お支払い期日：<%= @pay_date %></div>
        <div style="">お振込み先：<%= @user.bank %>　<%= @user.branch %>　<%= @user.account_type %>　<%= @user.number %>　<%= @user.name %></div>
      </div>
    </div>
  </body>
</html>

app/views/sells/search.html.erb
<div class="box_container">
  <div class="section-title">
    得意先別の集計
  </div>
  <div class="box-center">
    <%= form_with url: sells_search_result_path, method: :get, local: true do %>
      <div class="box-wrap">
        <%= label_tag :customer_id, "得意先", class: "box-label" %><br>
        <%= select_tag :customer_id, options_from_collection_for_select(@customers, :id, :company, params.fetch(:customer_id, 1)), prompt: "得意先を選択", required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :start_date, "開始日", class: "box-label" %><br>
        <%= date_field_tag :start_date, params[:start_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap">
        <%= label_tag :end_date, "終了日", class: "box-label" %><br>
        <%= date_field_tag :end_date, params[:end_date], required: true, class: "box-content" %>
      </div>

      <div class="box-wrap-btn">
        <%= submit_tag "検索", class: "box-content" %>
      </div>
    <% end %>

    <div class="back">
      <%= link_to  '前のページに戻る', root_path %>
    </div>
  </div>
</div>

app/views/sells/search_result.html.erb
<div class="table_container">
  <div class="section-title">
    得意先別の集計
  </div>

  <div class="sub-title">
    <%= @customer.company %>への納品<br>
    <%= @start_date %> ～ <%= @end_date %>
  </div>

  <table class="table-bordered">
    <thead>
      <tr>
        <th>日付</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody>
      <% @receipts.each do |receipt| %>
        <tr>
          <td class="table-day"><%= receipt.transaction_date %></td>
          <td class="table-price"><%= receipt.total_price %></td>
        </tr>
      <% end %>  
    </tbody>
    <tfoot>
      <td class="table-total-text">合計</td>
      <td class="table-price"><%= @receipts.sum(&:total_price) %></td>
    </tfoot>
  </table>

  <div class="back">
    <%= link_to  '前のページに戻る', sells_search_path %>
  </div>
</div>

app/views/sells/show.html.erb
<div class="a5_container"> 

  <div class="pdf-title">
    納品書
  </div>

  <div class="pdf-header">
    <div class="pdf-header-left">
      <div class="pdf-left-company">
        <div class="pdf-company-name">
          
        </div>
        <div class="pdf-company-tag">
          御中
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu">
          納品日
        </div>
        <div class="pdf-pay-text">
          <%= @sell.transaction_date %>
        </div>
      </div>
      <div class="pdf-pay-content">
        <div class="pdf-pay-menu">
          合計金額
        </div>
        <div class="pdf-pay-text">
          <%= @sell.total_price %>円
        </div>
      </div>
    </div>

    <div class="pdf-header-right">
      <div class="pdf-right-date">
        作成日：<%= Date.today %>
      </div>
      <div class="pdf-right-company">
        <%= @user.company %><br><br>
        住所：<%= @user.city %><%= @user.address %><br>
        電話番号：<%= @user.phone %><br>
        担当：<%= @user.manager %>
      </div>
    </div>
  </div>

  <div class="">
    <table class="pdf-table">
      <thead class="pdf-table-header">
        <tr>
          <th>商品名</th>
          <th>数量</th>
          <th>単位</th>
          <th>単価</th>
          <th>金額</th>
        </tr>
      </thead>
      <tbody>
        <% @sell.sell_items.each do |sell_item| %>
          <tr>
            <td><%= @items.find { |item| item.id == sell_item.item_id }&.item_name || "不明" %></td>
            <td class="pdf-table-quantity"><%= sell_item.quantity %></td>
            <td class="pdf-table-unit"><%= @items.find { |item| item.id == sell_item.item_id }&.unit || "不明" %></td>
            <td class="pdf-table-price"><%= sell_item.item_price %></td>
            <td class="pdf-table-price"><%= sell_item.item_total_price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="back">
    <%= link_to '前のページに戻る', sells_order_index_path %>
  </div>